# render.yaml
services:
  - type: web
    name: alpha-blog
    runtime: ruby
    plan: free           # use starter/standard+ to enable preDeployCommand
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bin/rails db:migrate"   # uncomment if you upgrade off Free
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alpha-blog-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false   # youâ€™ll paste this during Blueprint creation
      - key: WEB_CONCURRENCY
        value: "2"

databases:
  - name: alpha-blog-db
    plan: free
