services:
  - type: web
    name: alpha-blog
    env: ruby
    region: oregon
    buildCommand: bundle install && bundle exec rails assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alpha-blog-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    releaseCommand: bundle exec rails db:migrate

databases:
  - name: alpha-blog-db
    region: oregon
    plan: free
